let plusBtn = document.querySelector('.plus_btn')
plusBtn.addEventListener('click', () => {
	let newForm = document.createElement('form')
	let newDiv = document.createElement('div')
	newDiv.classList.add('grade')

	//製作html標籤
	let newInput1 = document.createElement('input')
	newInput1.setAttribute('type', 'text')
	newInput1.setAttribute('list', 'opt')
	newInput1.setAttribute('placeholder', 'class category')
	newInput1.classList.add('class_type')
	let newInput2 = document.createElement('input')
	newInput2.setAttribute('type', 'text')
	newInput2.setAttribute('placeholder', 'class number')
	newInput2.classList.add('class_number')
	let newInput3 = document.createElement('input')
	newInput3.setAttribute('type', 'number')
	newInput3.setAttribute('placeholder', 'credits')
	newInput3.setAttribute('max', '6')
	newInput3.setAttribute('min', '1')
	newInput3.classList.add('class_credit')
	newInput3.addEventListener('change', e => {
		setGPA()
	})

	let newSelect = document.createElement('select')
	newSelect.classList.add('select')
	var opt1 = document.createElement('option')
	opt1.setAttribute('value', '')
	let textNode1 = document.createTextNode('')
	opt1.appendChild(textNode1)
	var opt2 = document.createElement('option')
	opt2.setAttribute('value', 'A')
	let textNode2 = document.createTextNode('A')
	opt2.appendChild(textNode2)
	var opt3 = document.createElement('option')
	opt3.setAttribute('value', 'A-')
	let textNode3 = document.createTextNode('A-')
	opt3.appendChild(textNode3)
	var opt4 = document.createElement('option')
	opt4.setAttribute('value', 'B+')
	let textNode4 = document.createTextNode('B+')
	opt4.appendChild(textNode4)
	var opt5 = document.createElement('option')
	opt5.setAttribute('value', 'B')
	let textNode5 = document.createTextNode('B')
	opt5.appendChild(textNode5)
	var opt6 = document.createElement('option')
	opt6.setAttribute('value', 'B-')
	let textNode6 = document.createTextNode('B-')
	opt6.appendChild(textNode6)
	var opt7 = document.createElement('option')
	opt7.setAttribute('value', 'C+')
	let textNode7 = document.createTextNode('C+')
	opt7.appendChild(textNode7)
	var opt8 = document.createElement('option')
	opt8.setAttribute('value', 'C')
	let textNode8 = document.createTextNode('C')
	opt8.appendChild(textNode8)
	var opt9 = document.createElement('option')
	opt9.setAttribute('value', 'C-')
	let textNode9 = document.createTextNode('C-')
	opt9.appendChild(textNode9)
	var opt10 = document.createElement('option')
	opt10.setAttribute('value', 'D+')
	let textNode10 = document.createTextNode('D+')
	opt10.appendChild(textNode10)
	var opt11 = document.createElement('option')
	opt11.setAttribute('value', 'D')
	let textNode11 = document.createTextNode('D')
	opt11.appendChild(textNode11)
	var opt12 = document.createElement('option')
	opt12.setAttribute('value', 'D-')
	let textNode12 = document.createTextNode('D-')
	opt12.appendChild(textNode12)
	var opt13 = document.createElement('option')
	opt13.setAttribute('value', 'F')
	let textNode13 = document.createTextNode('F')
	opt13.appendChild(textNode13)

	newSelect.appendChild(opt1)
	newSelect.appendChild(opt2)
	newSelect.appendChild(opt3)
	newSelect.appendChild(opt4)
	newSelect.appendChild(opt5)
	newSelect.appendChild(opt6)
	newSelect.appendChild(opt7)
	newSelect.appendChild(opt8)
	newSelect.appendChild(opt9)
	newSelect.appendChild(opt10)
	newSelect.appendChild(opt11)
	newSelect.appendChild(opt12)
	newSelect.appendChild(opt13)

	newSelect.addEventListener('change', e => {
		setGPA()
		changeColor(e.target)
	})

	let newButton = document.createElement('button')
	newButton.classList.add('trash_button')
	let newIcon = document.createElement('i')
	newIcon.classList.add('bi')
	newIcon.classList.add('bi-trash3')
	newButton.appendChild(newIcon)

	newButton.addEventListener('click', e => {
		e.preventDefault()
		e.target.parentNode.parentNode.style.animation =
			'scaleDown .5s ease forwards'
		e.target.parentNode.parentNode.addEventListener('animationend', e => {
			e.target.remove()
			setGPA()
		})
	})

	newDiv.appendChild(newInput1)
	newDiv.appendChild(newInput2)
	newDiv.appendChild(newInput3)
	newDiv.appendChild(newSelect)
	newDiv.appendChild(newButton)
	newForm.appendChild(newDiv)
	document.querySelector('.all_inputs').appendChild(newForm)
	newForm.style.animation = 'scaleUp .7s ease forwards'
})

let allTrashBtn = document.querySelectorAll('.trash_button')
allTrashBtn.forEach(trashBtn => {
	trashBtn.addEventListener('click', e => {
		e.target.parentNode.parentNode.classList.add('remove')
	})
})
allTrashBtn.forEach(trashBtn => {
	let form = trashBtn.parentNode.parentNode
	form.addEventListener('transitionend', () => {
		form.remove()
		setGPA()
	})
})
